originData_path: E:/1_Research/3_UAV_2/2_data/2_new_data
output_path: ../../trained_model/4_noiseVar/noNoise
csv_savePath: ../../results/4_noiseVar
pkl_savePath: ../../pkl_dataset/4_noiseVar
mfcc_setting:
    num_filter: 201
    num_cep: 201
    winlen: 1
    winstep: 0.5
    fs: 44100
    mfcc_d1_switch: False
    mfcc_d2_switch: False
    highfreq_limit: 8000
