name: drone_auth
channels:
  - defaults
  - conda-forge
dependencies:
  - pip>=21.0
  - python=3.8.12
  - yaml==0.2.5
  - pip:
    - matplotlib==3.5.0
    - numpy==1.21.2
    - pandas==1.3.5
    - seaborn==0.11.2
    - wave==0.0.2
    - scikit-learn==1.0.2
    - scipy==1.7.3

