originData_path: E:/1_Research/3_UAV_2/2_data/2_new_data
output_path: ../../trained_model/2_filterVar/8d_2_all
csv_savePath: ../../results/3_filterVar_noise/8d_2_all
pkl_savePath: ../../pkl_dataset/3_filterVar_noise
mfcc_setting:
    num_filter: 
    num_cep: 
    winlen: 1
    winstep: 0.5
    fs: 44100
    mfcc_d1_switch: True
    mfcc_d2_switch: False
    highfreq_limit: 8000
    portion: 3
