originData_path: E:/1_Research/3_UAV_2/2_data/2_new_data
output_path: 
csv_savePath: 
pkl_savePath: ../pkl_dataset/1_timeVar
pkl_fileName: 
mfcc_setting:
    num_filter: 50
    num_cep: 50
    winlen: 
    winstep: 
    fs: 44100
    mfcc_d1_switch: True
    mfcc_d2_switch: True
    highfreq_limit: 8000
