originData_path: E:/1_Research/3_UAV_2/2_data/2_new_data
output_path: ../../trained_model/5_attack
csv_savePath: 
pkl_savePath: ../../pkl_dataset/5_attack
pkl_fileName: _201nf_201nc_1.00wl_0.50ws_8000lim.pkl
mfcc_setting:
    num_filter: 201
    num_cep: 201
    winlen: 1
    winstep: 0.5
    fs: 44100
    mfcc_d1_switch: False
    mfcc_d2_switch: False
    highfreq_limit: 8000
